### ISSUE TITLE
current user name does not display in the Sidebar

### ISSUE THREAD

**Issue by rkumar** [adrianthedev/avobookr#2]
Both in your video, and in the app I tried out based on the video, the sidebar shows "Avo user". Going through the source of avo, i found "Avo user" is printed if `@user` is nil in the `sidebar_profile_component.rb`. I could not locate where the value was coming from, but finally got it running by setting @user to `Avo::App.context[:current_user]` if nil. 

How come the user name is not being printed. Is there some missing step ? Thanks a lot.

**Comment by rkumar** [comment]
I just discovered that by going to `avo.rb` and setting `config.current_user_method = :current_user`, the username will display in the sidebar.

**Comment by adrianthedev** [comment]
Yup. That's correct!
